# Generated by Django 5.1.4 on 2025-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='desarrollador',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='desarrollador',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='desarrollador',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cliente',
            name='mensaje',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='No registrado', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='proyecto',
            field=models.CharField(default='No registrado', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='company',
            field=models.CharField(default='Sin empresa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='rol',
            field=models.CharField(default='sin empresa', max_length=100),
            preserve_default=False,
        ),
    ]
