# Generated by Django 5.1.4 on 2025-01-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], max_length=50)),
                ('cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='desarrollador',
            old_name='name',
            new_name='nombre',
        ),
    ]
