# Generated by Django 5.1.4 on 2025-01-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_company_cliente_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_fin',
            new_name='fecha_de_fin',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_inicio',
            new_name='fecha_de_inicio',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre',
            new_name='nombre_proyecto',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
